/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.pjwstk.sri.lab08;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2018-6-15")
public class OrderItem implements org.apache.thrift.TBase<OrderItem, OrderItem._Fields>, java.io.Serializable, Cloneable, Comparable<OrderItem> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("OrderItem");

  private static final org.apache.thrift.protocol.TField PRODUCT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("productId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField NUMBER_OF_PIECES_FIELD_DESC = new org.apache.thrift.protocol.TField("numberOfPieces", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new OrderItemStandardSchemeFactory());
    schemes.put(TupleScheme.class, new OrderItemTupleSchemeFactory());
  }

  public long productId; // required
  public int numberOfPieces; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PRODUCT_ID((short)1, "productId"),
    NUMBER_OF_PIECES((short)2, "numberOfPieces");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PRODUCT_ID
          return PRODUCT_ID;
        case 2: // NUMBER_OF_PIECES
          return NUMBER_OF_PIECES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PRODUCTID_ISSET_ID = 0;
  private static final int __NUMBEROFPIECES_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PRODUCT_ID, new org.apache.thrift.meta_data.FieldMetaData("productId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.NUMBER_OF_PIECES, new org.apache.thrift.meta_data.FieldMetaData("numberOfPieces", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(OrderItem.class, metaDataMap);
  }

  public OrderItem() {
  }

  public OrderItem(
    long productId,
    int numberOfPieces)
  {
    this();
    this.productId = productId;
    setProductIdIsSet(true);
    this.numberOfPieces = numberOfPieces;
    setNumberOfPiecesIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public OrderItem(OrderItem other) {
    __isset_bitfield = other.__isset_bitfield;
    this.productId = other.productId;
    this.numberOfPieces = other.numberOfPieces;
  }

  public OrderItem deepCopy() {
    return new OrderItem(this);
  }

  @Override
  public void clear() {
    setProductIdIsSet(false);
    this.productId = 0;
    setNumberOfPiecesIsSet(false);
    this.numberOfPieces = 0;
  }

  public long getProductId() {
    return this.productId;
  }

  public OrderItem setProductId(long productId) {
    this.productId = productId;
    setProductIdIsSet(true);
    return this;
  }

  public void unsetProductId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PRODUCTID_ISSET_ID);
  }

  /** Returns true if field productId is set (has been assigned a value) and false otherwise */
  public boolean isSetProductId() {
    return EncodingUtils.testBit(__isset_bitfield, __PRODUCTID_ISSET_ID);
  }

  public void setProductIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PRODUCTID_ISSET_ID, value);
  }

  public int getNumberOfPieces() {
    return this.numberOfPieces;
  }

  public OrderItem setNumberOfPieces(int numberOfPieces) {
    this.numberOfPieces = numberOfPieces;
    setNumberOfPiecesIsSet(true);
    return this;
  }

  public void unsetNumberOfPieces() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __NUMBEROFPIECES_ISSET_ID);
  }

  /** Returns true if field numberOfPieces is set (has been assigned a value) and false otherwise */
  public boolean isSetNumberOfPieces() {
    return EncodingUtils.testBit(__isset_bitfield, __NUMBEROFPIECES_ISSET_ID);
  }

  public void setNumberOfPiecesIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __NUMBEROFPIECES_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PRODUCT_ID:
      if (value == null) {
        unsetProductId();
      } else {
        setProductId((Long)value);
      }
      break;

    case NUMBER_OF_PIECES:
      if (value == null) {
        unsetNumberOfPieces();
      } else {
        setNumberOfPieces((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PRODUCT_ID:
      return Long.valueOf(getProductId());

    case NUMBER_OF_PIECES:
      return Integer.valueOf(getNumberOfPieces());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PRODUCT_ID:
      return isSetProductId();
    case NUMBER_OF_PIECES:
      return isSetNumberOfPieces();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof OrderItem)
      return this.equals((OrderItem)that);
    return false;
  }

  public boolean equals(OrderItem that) {
    if (that == null)
      return false;

    boolean this_present_productId = true;
    boolean that_present_productId = true;
    if (this_present_productId || that_present_productId) {
      if (!(this_present_productId && that_present_productId))
        return false;
      if (this.productId != that.productId)
        return false;
    }

    boolean this_present_numberOfPieces = true;
    boolean that_present_numberOfPieces = true;
    if (this_present_numberOfPieces || that_present_numberOfPieces) {
      if (!(this_present_numberOfPieces && that_present_numberOfPieces))
        return false;
      if (this.numberOfPieces != that.numberOfPieces)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_productId = true;
    list.add(present_productId);
    if (present_productId)
      list.add(productId);

    boolean present_numberOfPieces = true;
    list.add(present_numberOfPieces);
    if (present_numberOfPieces)
      list.add(numberOfPieces);

    return list.hashCode();
  }

  @Override
  public int compareTo(OrderItem other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetProductId()).compareTo(other.isSetProductId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProductId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.productId, other.productId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNumberOfPieces()).compareTo(other.isSetNumberOfPieces());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNumberOfPieces()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.numberOfPieces, other.numberOfPieces);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("OrderItem(");
    boolean first = true;

    sb.append("productId:");
    sb.append(this.productId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("numberOfPieces:");
    sb.append(this.numberOfPieces);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class OrderItemStandardSchemeFactory implements SchemeFactory {
    public OrderItemStandardScheme getScheme() {
      return new OrderItemStandardScheme();
    }
  }

  private static class OrderItemStandardScheme extends StandardScheme<OrderItem> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, OrderItem struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PRODUCT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.productId = iprot.readI64();
              struct.setProductIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NUMBER_OF_PIECES
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.numberOfPieces = iprot.readI32();
              struct.setNumberOfPiecesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, OrderItem struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(PRODUCT_ID_FIELD_DESC);
      oprot.writeI64(struct.productId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(NUMBER_OF_PIECES_FIELD_DESC);
      oprot.writeI32(struct.numberOfPieces);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class OrderItemTupleSchemeFactory implements SchemeFactory {
    public OrderItemTupleScheme getScheme() {
      return new OrderItemTupleScheme();
    }
  }

  private static class OrderItemTupleScheme extends TupleScheme<OrderItem> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, OrderItem struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetProductId()) {
        optionals.set(0);
      }
      if (struct.isSetNumberOfPieces()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetProductId()) {
        oprot.writeI64(struct.productId);
      }
      if (struct.isSetNumberOfPieces()) {
        oprot.writeI32(struct.numberOfPieces);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, OrderItem struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.productId = iprot.readI64();
        struct.setProductIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.numberOfPieces = iprot.readI32();
        struct.setNumberOfPiecesIsSet(true);
      }
    }
  }

}

